name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Автоформатирование кода с помощью Black
        run: |
          black .

      - name: Запуск статического анализа кода
        run: |
          pylint .
